title: The Amazing World of a Computer Scientist
author: GitHub User @Jagod101 aka Seth Rogen
email: jagod101@mail.chapman.edu
description: > # this means to ignore newlines until "baseurl:"
  I was told I needed to edit this text field, so that it the result.
  I think that GitHub is an amazing resource, so all this implementation is insane!
  Looking forward to learning more, so follow along in the Amazing World of a Computer Scientist

# social links
instagram_username: zjagoda
github_username:  jagod101

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
